ARG FEDORA_MAJOR_VERSION=stable

FROM quay.io/fedora/fedora-coreos:${FEDORA_MAJOR_VERSION}

RUN sudo echo "net.bridge.bridge-nf-call-iptables = 1" > /etc/sysctl.d/k8s.conf && \
    sudo echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf && \
    sudo echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/k8s.conf

RUN dnf in -y kubernetes1.33 kubernetes1.33-kubeadm kubernetes1.33-client \
              crio \
	      containernetworking-plugins && \

    dnf clean all
