ARG FEDORA_MAJOR_VERSION=stable

FROM quay.io/fedora/fedora-coreos:${FEDORA_MAJOR_VERSION}

RUN curl -s -o /etc/yum.repos.d/tailscale.repo https://pkgs.tailscale.com/stable/centos/9/tailscale.repo

COPY k8s.conf /etc/sysctl.d/k8s.conf
COPY k8s-mod.conf /etc/modules-load.d/k8s.conf

RUN dnf in -y kubernetes1.33 kubernetes1.33-kubeadm kubernetes1.33-client \
	crio \
	containernetworking-plugins \
	haproxy \
	keepalived \
	tailscale && \
	dnf clean all
