ARG FEDORA_MAJOR_VERSION=42
ARG FEDORA_DE=silverblue

FROM quay.io/fedora-asahi-remix-atomic-desktops/${FEDORA_DE}:${FEDORA_MAJOR_VERSION}

RUN curl -s -o /etc/yum.repos.d/tailscale.repo https://pkgs.tailscale.com/stable/centos/9/tailscale.repo

RUN dnf remove -y firefox tcl

RUN dnf in -y alacritty \
        autoconf \
	bison \
	clang \
	flex \
	openssl-devel \
        hyprland \
	gdb \
	glib \
	libvirt \
	libvirt-client \
	libzstd-devel \
	lld \
	llvm \
	lua5.1-lpeg \
	make \
	mutt \
	neovim \
	ostree-devel \
	pre-commit \
	python3-pip \
	qemu \
	qemu-kvm \
	ripgrep \
	tmux \
	virt-install \
	zsh \
	waybar \
	tailscale && \

	dnf up -y && \
	dnf clean all
